name: moodpick
description: "Hello world but it's more than just that"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_svg: ^2.0.5
  google_sign_in: ^6.2.1
  supabase_auth_ui: ^0.4.4
  supabase_flutter: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.svg
    - assets/font/inter.ttf

  fonts:
    - family: Inter
      fonts:
        - asset: assets/font/inter.ttf
          style: italic
